### ISSUE TITLE
read SAS token from Azure KeyVault (static provisioning support)

### ISSUE THREAD

**Issue by lenisha** [csi-driver/blobfuse-csi-driver#69]
**Describe the solution you'd like in detail**
Add ability to read SAS tokens that are mounted by Azure KeyVault flexvolume to some path instead of K8S secrets

**Comment by andyzhangx** [comment]
thanks, 
/assign @ZeroMagic

**Comment by andyzhangx** [comment]
hi @lenisha 
After my second thought, read from `mounted file which contains sas token` is not secure as k8s secret, I don't think that's a good idea.
We will support sas token read from k8s secret in our plan.

**Comment by andyzhangx** [comment]
another way is read one key vault value from inside blobfuse driver directly, need to evaluate first and also needs to know, how many customers wants this feature.

**Comment by andyzhangx** [comment]
could refer to https://github.com/deislabs/secrets-store-csi-driver/blob/master/pkg/providers/azure/provider.go for reading Azure key vault value from inside blobfuse driver 
cc @ZeroMagic

**Comment by andyzhangx** [comment]
@lenisha we would like to support reading storage account key or sas token from keyvault, the new filed names are like following:
```
  csi:
    driver: blobfuse.csi.azure.com
    readOnly: false
    volumeHandle: arbitrary-volumeid
    volumeAttributes:
      containerName: EXISTING_CONTAINER_NAME
      storageAccountName: EXISTING_STORAGE_ACCOUNT_NAME
      keyVaultURL: xxx
      keyVaultSecretName: xxx
      keyVaultSecretVersion: xxx
```
