### ISSUE TITLE
a few issues in keyvault scenario

### ISSUE THREAD

**Issue by andyzhangx** [csi-driver/blobfuse-csi-driver#75]
**What happened**:
1. I got following error when try to follow up with guide: https://github.com/csi-driver/blobfuse-csi-driver/blob/master/deploy/example/keyvault/README.md

```
kubelet, k8s-agentpool-32686255-0  MountVolume.SetUp failed for volume "pv-blobfuse" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Unknown desc = failed to use vaultURL(/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourcegroups/andy-mg1160alpha3/providers/Microsoft.KeyVault/vaults/andytestx), sercretName(sastoken), secretVersion() to get secret: keyvault.BaseClient#GetSecret: Failure preparing request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL /subscriptions/xxx/resourcegroups/andy-mg1160alpha3/providers/Microsoft.KeyVault/vaults/andytestx
```

2. following secret config is not necessary in the config
https://github.com/csi-driver/blobfuse-csi-driver/blob/f554f91d2ed1c09de682e106565a99961067f11e/deploy/example/keyvault/pv-blobfuse-csi-keyvault.yaml#L21-L23

My config is like this:
```
piVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blobfuse
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain #If set as "Delete" container would be removed after pvc deletion
  csi:
    driver: blobfuse.csi.azure.com
    readOnly: false
    volumeHandle: arbitrary-volumeid
    volumeAttributes:
      containerName: public
      storageAccountName: fde1626e2ba5e11e999ae36
      keyVaultURL: /subscriptions/xxx/resourcegroups/andy-mg1160alpha3/providers/Microsoft.KeyVault/vaults/andytestx
      keyVaultSecretName: sastoken
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign @ZeroMagic
